### PR TITLE
project finished

### PR DESCRIPTION
**Pull request by Jinboi**
Project Finished! 

As always—thank you for your guidance!

### CODE REVIEW

**Comment by Jinboi** [comment]
Hi SteveTV,

Thank you for reviewing my project!

Please review STUDY.ConsoleP.ExcelReaderTryTwo

The other project is my failed attempt of tackling on this project.

I'll make sure to only upload the final-and-completed project next time. 

Thank you!

**Comment by stevietv** [comment]
Hi @Jinboi - in that case could you push up another commit to the same branch that removes the un-needed project?

**Comment by Jinboi** [comment]
Certainly! I've re-commited after deleting unnecessary files

**Comment by stevietv** [comment]
Closing as approved

**Pull request closed without merging**
