### PR TITLE
ExcelReader.Lonchanick

### PR DESCRIPTION
**Pull request by lonchanick**
Hey! C# Academy Crew!

### CODE REVIEW

**Comment by lonchanick** [comment]
Hey Crew!
Any problem with this project?
Regards!!!

**Comment by lonchanick** [comment]
codacy fixed, execute this from cmd ..

**Comment by lonchanick** [comment]
You can avoid the errors about the licence executing the program from the console, somewhat like >> dotnet run 
Thanks :)!

**Comment by TheCSharpAcademy** [comment]
@lonchanick well done, it works great 😎

I think my only advice here would be to name your methods more clearly. **Test(), Get()** aren't very descriptive. What are we getting? What are we testing? You did it well with **PrintPersons()** as it tells exactly what's going on 🤓

**Comment by lonchanick** [comment]
You'r right, I'll bear in mind next time
ty :)

**Pull request merged**
