### PR TITLE
Project finished

### PR DESCRIPTION
**Pull request by jollejonas**
Looking forward to your review 😄

### CODE REVIEW

**Comment by TheCSharpAcademy** [comment]
@jollejonas Project approved! 😄✅ Clean, tidy and to the point, well done. 🫡 How did you go working with EP Plus, was it hard?

I just had a look at your projects and realized you need to complete your Flashcards project to keep earning belts, if you care about that 🤓

See you in the next project!

**Comment by jollejonas** [comment]
> @jollejonas Project approved! 😄✅ Clean, tidy and to the point, well done. 🫡 How did you go working with EP Plus, was it hard?
> 
> I just had a look at your projects and realized you need to complete your Flashcards project to keep earning belts, if you care about that 🤓
> 
> See you in the next project!

@TheCSharpAcademy I can't submit the Flashcard Project in the homepage, it says that it is already completed. I have an open pull request on the flashcard project, just waiting to get reviewed. I think the issue might have been, that I was too slow to update the code after the first review. I've tried to ask for help on discord, but still not working, so I'm just trying to be patient 😄 

And thanks for the review. I fell that EP plus seemed quite simple, at least for this project, so it didn't take too long, to understand how it works. 😄

**Comment by TheCSharpAcademy** [comment]
@jollejonas Sorry about that and thanks for letting me know. Yes, it looks like your project was archived and there's a bug that marks archived as completed. I'll go on and review your project 🫡

**Comment by jollejonas** [comment]
@TheCSharpAcademy Thanks! 😄

**Pull request closed without merging**
