### PR TITLE
done

### PR DESCRIPTION
**Pull request by kwm0304**

### CODE REVIEW

**Review by Doc415 — CHANGES_REQUESTED** [review]
Hey
The app does not create the db in mssql, i had to create it manualy, this should be fixed
when i give the path to csv files app throws exception
image

**Comment by kwm0304** [comment]
@Doc415  Hey I (hopefully)fixed the license exception and am creating the db on start now

**Review by Doc415 — CHANGES_REQUESTED** [review]
hey 
player stat excel file throws exception 
image

**Comment by kwm0304** [comment]
image

@Doc415  Should be good now

**Review by Doc415 — APPROVED** [review]
Good to go 👌

**Pull request closed without merging**
